# Generated by Django 2.2.3 on 2019-07-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqTitle', models.CharField(max_length=50, verbose_name='reqTitle')),
                ('reqDesc', models.CharField(max_length=300, verbose_name='reqDesc')),
                ('reqStatus', models.CharField(max_length=10, verbose_name='reqStatus')),
                ('reqRemark', models.CharField(max_length=200, verbose_name='reqRemark')),
                ('reqCreateTime', models.DateTimeField(auto_now_add=True, verbose_name='reqCreateTime')),
            ],
            options={
                'db_table': 'hj_requirement',
                'ordering': ['-reqCreateTime'],
            },
        ),
    ]
